### ISSUE TITLE
The user mention format starts with "@"?

### ISSUE THREAD

**Issue by mpses** [SeikoStudentCouncil/SlackArchiveBot#15]
Now the user mention format is like **just** `飼沼 隼_技術部門長`, and won't it be like `@飼沼 隼_技術部門長`? @miko-misa

**Comment by akimasa-l** [comment]
I think we don't need using `name_role` format. If we want to mention someone, we just use like @mpses . Everyone knows who is `飼沼 隼` and `技術部門長` so it is too redundant.

**Comment by miko-misa** [comment]
Seriously? I forgot to write down that process.I I think it's better to start with '@'.

**Comment by mpses** [comment]
Alright I committed and pr #21 is open.
