### ISSUE TITLE
ReferenceError: BACKUP_SHEET_ID is not defined

### ISSUE THREAD

**Issue by miko-misa** [SeikoStudentCouncil/SlackArchiveBot#22]
ReferenceError: BACKUP_SHEET_ID is not defined（行 18、ファイル「ArchiveMessage」）
ど　う　し　て

**Comment by mpses** [comment]
What Properties are set in the GAS Project?

**Comment by miko-misa** [comment]
BACKUP_SHEET_ID
CHANNNEL_ADMIN_AUTH_TOKEN
CHANNNEL_TOKEN
