### ISSUE TITLE
Exception: 共有ドライブ アイテムではこの操作を利用できません。

### ISSUE THREAD

**Issue by miko-misa** [SeikoStudentCouncil/SlackArchiveBot#25]
Exception: 共有ドライブ アイテムではこの操作を利用できません。（行 266、ファイル「ArchiveMessage」）

**Comment by mpses** [comment]
```javascript
itr.next().setTrashed(true)
```
may resolve this issue.

**Comment by mpses** [comment]
I'll open the pr.

**Comment by mpses** [comment]
I merged the pr into `main`, which may resolve #25.
