### ISSUE TITLE
The format of the downloaded file is wrong.

### ISSUE THREAD

**Issue by miko-misa** [SeikoStudentCouncil/SlackArchiveBot#28]
https://files.slack.com/files-pri/T01BD0XA1PF-F02AJEKA6PL/image.png

**Comment by mpses** [comment]
In `downloadData()`, there is something wrong with following;
```javascript
258 | var options = {
259 |     "headers": { 'Authorization': 'Bearer ' + CHANNNEL_ADMIN_AUTH_TOKEN }
260 |   };
... |
262 | var response = UrlFetchApp.fetch(url, options);
263 | var fileBlob = response.getBlob().setName(fileName);
```

**Comment by mpses** [comment]
Saved files are like this;
`<!DOCTYPE html><html lang="en-US" class="" data-primer><head><link href="https://a.slack-edge.com/`...

**Comment by akimasa-l** [comment]
I don't know what the actual format that you want(because I don't have right to access the Google Apps Script Project), but if you want to detect HTML file and other file(may be you actually want to get png file?), you can write code like this:

```js
const response = UrlFetchApp.fetch(url, options);
Logger.log(typeof response); // -> HTTPResponse
const headers=response.getHeaders();
Logger.log(JSON.stringify(headers,undefined,4))
/* 
{
    "Content-Type": "text/html; charset=UTF-8",
    "Cache-Control": "private, max-age=0",
    "Date": "Mon, 09 Aug 2021 04:56:11 GMT",
    ....
}
*/
if(headers["Content-Type"]==="text/html; charset=UTF-8"){// if response is html...
  //do something
}else{ // if response is not html....
  //do something
}
```

You can check the [Google official document][d].
 
[d]:https://developers.google.com/apps-script/reference/url-fetch/http-response#getHeaders()

**Comment by akimasa-l** [comment]
If you are good at Regular Expression, you can write the code like this.

```js
const response = UrlFetchApp.fetch(url, options);
Logger.log(typeof response); // -> HTTPResponse
const headers=response.getHeaders();
Logger.log(JSON.stringify(headers,undefined,4))
/* 
{
    "Content-Type": "text/html; charset=UTF-8",
    "Cache-Control": "private, max-age=0",
    "Date": "Mon, 09 Aug 2021 04:56:11 GMT",
    ....
}
*/

const isHtml=/$text\/html/
if(isHtml.test(headers)){// if response is html...
  //do something
}else{ // if response is not html....
  //do something
}

```

Because the charset is sometime not UTF-8, so I recommend this style.

**Comment by mpses** [comment]
Thanks @akimasa-l, we are trying to get FILES ON Slack by accessing Slack File download URL, but only to get these files for all cases.

**Comment by mpses** [comment]
solved.
