### ISSUE TITLE
file.alternateLink is null

### ISSUE THREAD

**Issue by mpses** [SeikoStudentCouncil/SlackArchiveBot#37]
On COLUMN `添付ファイル`, individual link string is `''`; like `', , , , , , , , , '`.

Now on function `downloadData()`,the  returned value `file.alteranateLink` seems to be `null`.
The return value from `.createfile` (`type file`) seems not to have method `alternateLink`, and `type driveFile` seems to.
We must consider to use this;
```javascript
  var file = folder.createFile(fileBlob);
  var driveFile = DriveApp.getFileById(file.getId())
  return driveFile.alternateLink;
```

**Comment by mpses** [comment]
pr was merged but issue has been unsolved yet 😢

**Comment by akimasa-l** [comment]
You had better use `getUrl()` method.
source:<https://developers.google.com/apps-script/reference/drive/file#getUrl()>
