### ISSUE TITLE
Unexpected error while downloading .HEIC

### ISSUE THREAD

**Issue by mpses** [SeikoStudentCouncil/SlackArchiveBot#48]
```javascript
Exception: Unexpected error: `https://files.slack.com/files-pri/T01BD0XA1PF-F01V7RZ0M41/download/img_4732.heic`
downloadData	@ ArchiveMessage.gs:271
getAllMessageInChannel	@ ArchiveMessage.gs:116
backUp	@ ArchiveMessage.gs:38
```
@akimasa-l

**Comment by akimasa-l** [comment]
Google's `UrlFetchApp` is unstable, there are some cases that they can't download specific file. It is not our problem, it is a problem with Google, so we don't have any solutions.

<https://issuetracker.google.com/issues/36760920?pli=1#comment10>

This is the same issue that they can't download `heic` file.

<https://issuetracker.google.com/issues/186132520>

**Comment by mpses** [comment]
Thanks @akimasa-l, let's put this aside for the time being.
The issue will be being temporarily closed.
