### ISSUE TITLE
Use slash command to archive messages of individual channels

### ISSUE THREAD

**Issue by akimasa-l** [SeikoStudentCouncil/SlackArchiveBot#62]

**Comment by akimasa-l** [comment]
![image](https://user-images.githubusercontent.com/62997105/129472547-5c7d58f4-341d-4f46-b248-d400e0ade11c.png)

ここから新しいデプロイを選んで

![image](https://user-images.githubusercontent.com/62997105/129472565-8cae8f5f-58d0-4081-b28b-31cef93c33de.png)

ここを **全員** にして

![image](https://user-images.githubusercontent.com/62997105/129472580-ddf18000-f2ff-4815-8739-6770d45246f1.png)

とりあえずそれをコピーして

![image](https://user-images.githubusercontent.com/62997105/129472606-378a59a0-fe58-4329-bb41-b6cdbf373632.png)


<https://api.slack.com/apps/> にアクセスして

![image](https://user-images.githubusercontent.com/62997105/129472636-ad7eb96f-88c4-41ea-bb0a-f529cbcd333a.png)

ここから

![image](https://user-images.githubusercontent.com/62997105/129472661-9cbde02a-02b4-4f20-84ff-736f23e86e11.png)

Request URLをコピーしたやつで埋めれば完成です

**Comment by mpses** [comment]
これ GAS 更新するたびに re-deploy しないといけないんですっけ

**Comment by akimasa-l** [comment]
デプロイしたときのコードが使われるので、コードを更新してウェブアプリも更新したくなったら更新してください
